# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    cmds:
      - task: tools:install
      - task: tidy
      - task: fmt
      - task: lint

  tools:install:
    - echo "Install local tools..."
    - (which gci > /dev/null) || GO111MODULE=off go install github.com/daixiang0/gci
    - (which gofumpt > /dev/null) || GO111MODULE=off go install mvdan.cc/gofumpt

  tidy:
    cmds:
      - echo "Tidy..."
      - go mod tidy

  fmt:
    cmds:
      - echo "Fmt..."
      - gofumpt -w .
      - gci write -s standard -s default -s "Prefix(github.com/golang-ninja-courses/defer-panic-mastery)" . 2> /dev/null

  lint:
    cmds:
      - task: lint:examples
      - task: lint:tasks

  lint:examples:
    - echo "Lint examples..."
    - golangci-lint run ./examples/...

  lint:tasks:
    - echo "Lint tasks..."
    - golangci-lint run ./tasks/...

  lint:dir:
    - echo "Lint..."
    - golangci-lint run {{.CLI_ARGS}}
